### ISSUE TITLE
Group capstone: set up Kanban board

### ISSUE THREAD

**Issue by Ferizad** [AnsarIbrahim/javascript-capstone-project#21]
- https://github.com/AnsarIbrahim/javascript-capstone-project/projects/1
- In this project 2 people: @AnsarIbrahim and @Ferizad.

**Comment by Shedrack-Sunday** [comment]
Hello Team!

Congratulations! 🎉 Your project is complete and you're ready to move on to finish the project! 🚀

![image](https://i.pinimg.com/originals/3d/d2/07/3dd207237b39dcacd832f94a35428255.gif)


## Highlights
-  Setup Kanban board with the required amount of tasks 👍 
- Each member assigned a task 👍 


## Optional Suggestions 💡
While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.
Cheers, and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread, and don't forget to tag me so I'll receive the notification.

As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
